
/*
/*===============================================================================
Overview – Exploratory Data Analysis (EDA) Queries
===============================================================================
This section contains exploratory SQL queries designed to understand the structure,
distribution, and baseline performance of the data within the gold schema. These 
queries help validate data quality, identify key metrics, and provide a foundation 
for further analytical modeling and reporting.

The analysis includes:

1. **Schema & Structure Inspection**
   - Listing tables and columns in the gold schema.
   - Previewing data from dim_customers, dim_products, and fact_sales.

2. **Basic Profile Metrics**
   - Unique countries, categories, subcategories, and products.
   - First and last order dates, order range, youngest and oldest customers.

3. **Global Business KPIs**
   - Total sales, total quantity, average selling price, total orders,
     total customers, total products.

4. **Customer Demographic Analysis**
   - Customer counts and average age by country.
   - Customer counts and average age by gender.

5. **Product-Level Analysis**
   - Total subcategories and products per category.
   - Category-level revenue and quantity metrics.

6. **Customer & Country Sales Contribution**
   - Revenue and quantity generated by each customer.
   - Revenue and quantity generated by each country.

7. **Ranking & Top/Bottom Performance**
   - Top 5 and bottom 5 products by revenue.
   - Top 10 customers by revenue.
   - Customers with the fewest orders placed.

These queries are intended for initial data discovery and validation before 
building dashboards, reports, or analytical models.
===============================================================================*/





select
	TABLE_NAME,
	COLUMN_NAME
	from INFORMATION_SCHEMA.COLUMNS
where TABLE_SCHEMA = 'gold'


select* from gold.dim_customers
select* from gold.dim_products
select* from gold.fact_sales


-- Retrieve a list of unique countries from which customers originate
SELECT DISTINCT 
    country 
FROM gold.dim_customers
ORDER BY country;

-- Retrieve a list of unique categories, subcategories, and products
SELECT DISTINCT 
    category, 
    subcategory, 
    product_name 
FROM gold.dim_products
ORDER BY category, subcategory, product_name;



-- Determine the first and last order date and the total duration in months
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales;

-- Find the youngest and oldest customer based on birthdate
SELECT
    MIN(birthdate) AS oldest_birthdate,
    DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers;


-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the Total number of Orders
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_name) AS total_products FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;

-- Report shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers;



-------------------------------------------------
-- Find total customersc and Average age by countries 
select 
country,
count(country) total_customers,
avg(datediff(year,birthdate,getdate())) average_age
from gold.dim_customers
group by country
order by total_customers desc

--Find total customers and Average age by gender 
select 
gender,
count(gender) total_customers,
avg(datediff(year,birthdate,getdate())) average_age
from gold.dim_customers
group by gender
order by total_customers desc


-- Find total subcategories,products and average cost by category
select
category,
count(distinct(subcategory)) total_subcategories,
count(product_id) total_prduct,
avg(cost) average_cost
from gold.dim_products
group by category
order by total_prduct desc


-- What is the total revenue and quantity generated for each category?
select 
p.category,
sum(s.quantity) total_quantity,
sum(s.sales_amount) total_sales
from gold.fact_sales s
left join gold.dim_products p 
on p.product_key = s.product_key
group by p.category
order by total_sales desc


-- What is the total revenue and quantity generated by each customer?
select
c.customer_key,
concat(first_name,' ',last_name) as customer_full_name,
sum(s.quantity) total_quantity,
sum(s.sales_amount) total_sales
from gold.fact_sales s
left join gold.dim_customers c 
on c.customer_key = s.customer_key
group by c.customer_key ,concat(first_name,' ',last_name)
order by total_sales desc



-- What is the total revenue and quantity generated by each country?
select
c.country,
sum(s.quantity) total_quantity,
sum(s.sales_amount) total_sales
from gold.fact_sales s
left join gold.dim_customers c 
on c.customer_key = s.customer_key
group by c.country 
order by total_sales desc
--------------------------------------Ranking-----------------------------------------------
-- Which 5 products Generating the Highest Revenue?
select top 5
p.product_name,
sum(s.sales_amount) total_sales
from gold.fact_sales s
left join gold.dim_products p 
on p.product_key = s.product_key
group by p.product_name
order by total_sales desc

-- What are the 5 worst-performing products in terms of sales?
select top 5
p.product_name,
sum(s.sales_amount) total_sales
from gold.fact_sales s
left join gold.dim_products p 
on p.product_key = s.product_key
group by p.product_name
order by total_sales asc

-- Find the top 10 customers who have generated the highest revenue
select top 10
c.customer_key,
concat(first_name,' ',last_name) as customer_full_name,
sum(s.sales_amount) total_sales
from gold.fact_sales s
left join gold.dim_customers c 
on c.customer_key = s.customer_key
group by c.customer_key ,concat(first_name,' ',last_name)
order by total_sales desc


-- The 3 customers with the fewest orders placed
select top 3
c.customer_key,
concat(first_name,' ',last_name) as customer_full_name,
count(distinct s.order_number) total_orders
from gold.fact_sales s
left join gold.dim_customers c 
on c.customer_key = s.customer_key
group by c.customer_key ,concat(first_name,' ',last_name)
order by total_orders asc





-- The 3 customers with the fewest orders placed
select top 3
c.customer_key,
concat(first_name,' ',last_name) as customer_full_name,
count(distinct s.order_number) total_orders
from gold.fact_sales s
left join gold.dim_customers c 
on c.customer_key = s.customer_key
group by c.customer_key ,concat(first_name,' ',last_name)
order by total_orders asc
*/

